; PlatformIO Project Configuration File2
; http://docs.platformio.org/page/projectconf.html

[platformio]
;default_envs = test
default_envs = stm32
;default_envs = genericGD32F130C8
;default_envs = genericGD32F103RC

[config]
variant = VARIANT_HOVERBOARD
build_flags_common =
    -D ${config.variant}

default_build_src =
    +<*>
    -<.git/>
    -<.svn/>
    -<hal/**>
    +<hal/hal.h>

;================================================================

[env:stm32]
platform        = ststm32
framework       = stm32cube
board           = genericSTM32F103RC
debug_tool      = stlink
upload_protocol = stlink

; Serial Port settings (make sure the COM port is correct)
monitor_port    = COM5
monitor_speed   = 115200

build_src_filter =
    ${config.default_build_src}
    +<hal/stm32>

build_flags =
    -D ${config.build_flags_common}

    -DUSE_HAL_DRIVER
    -DSTM32F103xE
    -I include/hal/stm32
    -lc
    -lm
    -g -ggdb        ; to generate correctly the 'firmware.elf' for STM STUDIO vizualization

[env:genericGD32]
platform = https://github.com/CommunityGD32Cores/platform-gd32.git
platform_packages = framework-spl-gd32@https://github.com/CommunityGD32Cores/gd32-pio-spl-package.git
framework = spl
debug_tool      = stlink
upload_protocol = stlink
monitor_port    = COM5
monitor_speed   = 19200

[env:genericGD32F130C8]
extends = env:genericGD32
board = genericGD32F130C8

build_src_filter =
    ${config.default_build_src}
    +<hal/Gd32F130C8T6>
    -<hal/Gd32F130C8T6/main.c>

build_flags =
    -D ${config.build_flags_common}
    -D GD32F130
    -D TARGET=1
    -I include/hal/Gd32F130C8T6

[env:genericGD32F103RC]
extends = env:genericGD32
board = genericGD32F103RC

build_src_filter =
    ${config.default_build_src}
    +<Board/Gd32F103RCT6>
    -<Board/Gd32F103RCT6/main.c>
    -<main.c>

build_flags =
    -D ${config.build_flags_common}
    -D GD32F103
    -I include/hal/Gd32F103RCT6

[env:test]
platform = native
test_framework = unity
;build_type = debug
;debug_test = *
build_flags =
    -std=c++20
    -DUNIT_TEST
