#include <config.h>

uint32_t PWM_FREQ;
uint32_t PWM_RES;

uint32_t DEAD_TIME;

/* Runtime definitions for motor enable flags. Defaults match previous behavior
 * (motors enabled unless explicitly disabled).
 */
uint8_t MOTOR_LEFT_ENA = 1;
uint8_t MOTOR_RIGHT_ENA = 1;

uint32_t PPM_NUM_CHANNELS;

uint32_t CONTROL_PPM_LEFT_ENABLED;
uint32_t CONTROL_PPM_RIGHT_ENABLED;
uint32_t CONTROL_PWM_LEFT_ENABLED;
uint32_t CONTROL_PWM_RIGHT_ENABLED;
uint32_t SUPPORT_BUTTONS_LEFT;
uint32_t SUPPORT_BUTTONS_RIGHT;

uint32_t CONTROL_ADC_ENABLED;
uint32_t CONTROL_ADC_INDEX;

uint32_t DEBUG_I2C_LCD;
uint32_t DEBUG_SERIAL_USART2_ENABLED;
uint32_t CONTROL_SERIAL_USART2_ENABLED;
uint32_t SIDEBOARD_SERIAL_USART2_ENABLED;
uint32_t SIDEBOARD_SERIAL_USART2_INDEX;
uint32_t DEBUG_SERIAL_USART3_ENABLED;

uint32_t ELECTRIC_BRAKE_ENABLE;
uint32_t ELECTRIC_BRAKE_MAX;
uint32_t ELECTRIC_BRAKE_THRES;

uint32_t CRUISE_CONTROL_SUPPORT;
uint32_t ADC_ALTERNATE_CONNECT;
uint32_t CONTROL_SERIAL_USART2_INDEX;
uint32_t IBUS_NUM_CHANNELS;
uint32_t CONTROL_SERIAL_USART3_ENABLED;
uint32_t CONTROL_SERIAL_USART3_INDEX;
uint32_t SIDEBOARD_SERIAL_USART3_ENABLED;
uint32_t SIDEBOARD_SERIAL_USART3_INDEX;
uint32_t CONTROL_IBUS;
uint32_t CONTROL_PPM_LEFT_INDEX;
uint32_t CONTROL_PPM_RIGHT_INDEX;
uint32_t SUPPORT_BUTTONS;
uint32_t CONTROL_PWM_LEFT_INDEX;
uint32_t CONTROL_PWM_RIGHT_INDEX;
uint32_t FEEDBACK_SERIAL_USART2_ENABLED;
uint32_t FEEDBACK_SERIAL_USART3_ENABLED;

uint32_t DUAL_INPUTS;

uint32_t DEBUG_SERIAL_PROTOCOL;
uint32_t IBUS_LENGTH;
uint32_t IBUS_COMMAND;
uint32_t CONTROL_NUNCHUK_ENABLED;
uint32_t SUPPORT_NUNCHUK;
uint32_t CONTROL_NUNCHUK_INDEX;
uint32_t GAMETRAK_CONNECTION_NORMAL;
uint32_t GAMETRAK_CONNECTION_ALTERNATE;

ControlVariant CONTROL_VARIANT;

uint32_t INVERT_L_DIRECTION;
uint32_t INVERT_R_DIRECTION;

uint32_t STANDSTILL_HOLD_ENABLE = 0;

uint32_t AUTO_CALIBRATION_ENA = 1;
uint32_t FLASH_WRITE_KEY;

uint32_t SERIAL_START_FRAME = 0xABCD;
uint32_t INPUT_BRK = -400;
uint32_t SUPPORT_LCD;

uint32_t MULTI_MODE_DRIVE;
uint32_t MULTI_MODE_DRIVE_M1_MAX = 175;
uint32_t MULTI_MODE_DRIVE_M1_RATE = 250;
uint32_t MULTI_MODE_M1_I_MOT_MAX = 4;
uint32_t MULTI_MODE_M1_N_MOT_MAX = 30;
uint32_t MULTI_MODE_DRIVE_M2_MAX = 500;
uint32_t MULTI_MODE_DRIVE_M2_RATE = 300;
uint32_t MULTI_MODE_M2_I_MOT_MAX = 8;
uint32_t MULTI_MODE_M2_N_MOT_MAX = 80;
uint32_t MULTI_MODE_DRIVE_M3_MAX = 1000;
uint32_t MULTI_MODE_DRIVE_M3_RATE = 450;
uint32_t MULTI_MODE_M3_I_MOT_MAX = I_MOT_MAX;
uint32_t MULTI_MODE_M3_N_MOT_MAX = N_MOT_MAX;

uint32_t TANK_STEERING;

void initialize_config() {
    PWM_FREQ = 16000;
    PWM_RES  = 64000000 / 2 / PWM_FREQ; // = 2000

    DEAD_TIME = 48;
}