#include <config.h>

uint32_t PWM_FREQ;
uint32_t PWM_RES;

uint32_t DEAD_TIME;

/* Runtime definitions for motor enable flags. Defaults match previous behavior
 * (motors enabled unless explicitly disabled).
 */
uint8_t MOTOR_LEFT_ENA = 1;
uint8_t MOTOR_RIGHT_ENA = 1;

uint32_t PPM_NUM_CHANNELS;

uint32_t CONTROL_PPM_LEFT_ENABLED;
uint32_t CONTROL_PPM_RIGHT_ENABLED;
uint32_t CONTROL_PWM_LEFT_ENABLED;
uint32_t CONTROL_PWM_RIGHT_ENABLED;
uint32_t SUPPORT_BUTTONS_LEFT;
uint32_t SUPPORT_BUTTONS_RIGHT;

uint32_t CONTROL_ADC_ENABLED;
uint32_t CONTROL_ADC_INDEX;

uint32_t DEBUG_I2C_LCD;
uint32_t DEBUG_SERIAL_USART2_ENABLED;
uint32_t CONTROL_SERIAL_USART2_ENABLED;
uint32_t SIDEBOARD_SERIAL_USART2_ENABLED;
uint32_t SIDEBOARD_SERIAL_USART2_INDEX;
uint32_t DEBUG_SERIAL_USART3_ENABLED;

uint32_t ELECTRIC_BRAKE_ENABLE;
uint32_t ELECTRIC_BRAKE_MAX;
uint32_t ELECTRIC_BRAKE_THRES;

uint32_t CRUISE_CONTROL_SUPPORT;
uint32_t ADC_ALTERNATE_CONNECT;
uint32_t CONTROL_SERIAL_USART2_INDEX;
uint32_t IBUS_NUM_CHANNELS;
uint32_t CONTROL_SERIAL_USART3_ENABLED;
uint32_t CONTROL_SERIAL_USART3_INDEX;
uint32_t SIDEBOARD_SERIAL_USART3_ENABLED;
uint32_t SIDEBOARD_SERIAL_USART3_INDEX;
uint32_t CONTROL_IBUS;
uint32_t CONTROL_PPM_LEFT_INDEX;
uint32_t CONTROL_PPM_RIGHT_INDEX;
uint32_t SUPPORT_BUTTONS;
uint32_t CONTROL_PWM_LEFT_INDEX;
uint32_t CONTROL_PWM_RIGHT_INDEX;
uint32_t FEEDBACK_SERIAL_USART2_ENABLED;
uint32_t FEEDBACK_SERIAL_USART3_ENABLED;

uint32_t DUAL_INPUTS;

uint32_t DEBUG_SERIAL_PROTOCOL;
uint32_t IBUS_LENGTH;
uint32_t IBUS_COMMAND;
uint32_t CONTROL_NUNCHUK_ENABLED;
uint32_t SUPPORT_NUNCHUK;
uint32_t CONTROL_NUNCHUK_INDEX;
uint32_t GAMETRAK_CONNECTION_NORMAL;
uint32_t GAMETRAK_CONNECTION_ALTERNATE;

ControlVariant CONTROL_VARIANT;

uint32_t INVERT_L_DIRECTION;
uint32_t INVERT_R_DIRECTION;

uint32_t STANDSTILL_HOLD_ENABLE = 0;

uint32_t AUTO_CALIBRATION_ENA = 1;
uint32_t FLASH_WRITE_KEY;

uint32_t SERIAL_START_FRAME = 0xABCD;
uint32_t INPUT_BRK = -400;
uint32_t SUPPORT_LCD;

uint32_t MULTI_MODE_DRIVE;
uint32_t MULTI_MODE_DRIVE_M1_MAX = 175;
uint32_t MULTI_MODE_DRIVE_M1_RATE = 250;
uint32_t MULTI_MODE_M1_I_MOT_MAX = 4;
uint32_t MULTI_MODE_M1_N_MOT_MAX = 30;
uint32_t MULTI_MODE_DRIVE_M2_MAX = 500;
uint32_t MULTI_MODE_DRIVE_M2_RATE = 300;
uint32_t MULTI_MODE_M2_I_MOT_MAX = 8;
uint32_t MULTI_MODE_M2_N_MOT_MAX = 80;
uint32_t MULTI_MODE_DRIVE_M3_MAX = 1000;
uint32_t MULTI_MODE_DRIVE_M3_RATE = 450;
uint32_t MULTI_MODE_M3_I_MOT_MAX = I_MOT_MAX;
uint32_t MULTI_MODE_M3_N_MOT_MAX = N_MOT_MAX;

uint32_t TANK_STEERING;

void initialize_config() {
    PWM_FREQ = 16000;
    PWM_RES  = 64000000 / 2 / PWM_FREQ; // = 2000

    DEAD_TIME = 48;

// ############################### VALIDATE SETTINGS ###############################
    if (CONTROL_VARIANT != VARIANT_ADC
            && CONTROL_VARIANT != VARIANT_USART
                && CONTROL_VARIANT != VARIANT_NUNCHUK
                    && CONTROL_VARIANT != VARIANT_PPM
                        && CONTROL_VARIANT != VARIANT_PWM
                            && CONTROL_VARIANT != VARIANT_IBUS
                                && CONTROL_VARIANT != VARIANT_HOVERCAR
                                    && CONTROL_VARIANT != VARIANT_HOVERBOARD
                                        && CONTROL_VARIANT != VARIANT_TRANSPOTTER
                                            && CONTROL_VARIANT != VARIANT_SKATEBOARD) {
        //#error Variant not defined! Please check platformio.ini or Inc/config.h for available variants.
        while (1) {  }
    }

    // General checks
    if (CONTROL_SERIAL_USART2_ENABLED && SIDEBOARD_SERIAL_USART2_ENABLED) {
        //#error CONTROL_SERIAL_USART2_ENABLED and SIDEBOARD_SERIAL_USART2_ENABLED not allowed, choose one.
        while(1) { }
    }

    if (CONTROL_SERIAL_USART3_ENABLED && SIDEBOARD_SERIAL_USART3_ENABLED) {
        //#error CONTROL_SERIAL_USART3_ENABLED and SIDEBOARD_SERIAL_USART3_ENABLED not allowed, choose one.
        while(1) { }
    }

    if (DEBUG_SERIAL_USART2_ENABLED && FEEDBACK_SERIAL_USART2_ENABLED) {
        //#error DEBUG_SERIAL_USART2_ENABLED and FEEDBACK_SERIAL_USART2_ENABLED not allowed, choose one.
        while(1) { }
    }

    if (DEBUG_SERIAL_USART3_ENABLED && FEEDBACK_SERIAL_USART3_ENABLED) {
        //#error DEBUG_SERIAL_USART3_ENABLED and FEEDBACK_SERIAL_USART3_ENABLED not allowed, choose one.
        while(1) { }
    }

    if (DEBUG_SERIAL_USART2_ENABLED && DEBUG_SERIAL_USART3_ENABLED) {
        //#error DEBUG_SERIAL_USART2_ENABLED and DEBUG_SERIAL_USART3_ENABLED not allowed, choose one.
        while(1) { }
    }

    if (CONTROL_PPM_LEFT_ENABLED && CONTROL_PPM_RIGHT_ENABLED) {
        //#error CONTROL_PPM_LEFT_ENABLED and CONTROL_PPM_RIGHT_ENABLED not allowed, choose one.
        while(1) { }
    }

    if (CONTROL_PWM_LEFT_ENABLED && CONTROL_PWM_RIGHT_ENABLED) {
        //#error CONTROL_PWM_LEFT and CONTROL_PWM_RIGHT not allowed, choose one.
        while(1) { }
    }

    if (SUPPORT_BUTTONS_LEFT && SUPPORT_BUTTONS_RIGHT) {
        //#error SUPPORT_BUTTONS_LEFT and SUPPORT_BUTTONS_RIGHT not allowed, choose one.
        while(1) { }
    }

    // LEFT cable checks
    if (CONTROL_ADC_ENABLED && (CONTROL_SERIAL_USART2_ENABLED || SIDEBOARD_SERIAL_USART2_ENABLED || FEEDBACK_SERIAL_USART2_ENABLED || DEBUG_SERIAL_USART2_ENABLED)) {
        //#error CONTROL_ADC_ENABLED and SERIAL_USART2 not allowed. It is on the same cable.
        while(1) { }
    }

    if (CONTROL_PPM_LEFT_ENABLED && (CONTROL_SERIAL_USART2_ENABLED || SIDEBOARD_SERIAL_USART2_ENABLED || FEEDBACK_SERIAL_USART2_ENABLED || DEBUG_SERIAL_USART2_ENABLED)) {
        //#error CONTROL_PPM_LEFT_ENABLED and SERIAL_USART2 not allowed. It is on the same cable.
        while(1) { }
    }

    if (CONTROL_PWM_LEFT_ENABLED && (CONTROL_SERIAL_USART2_ENABLED || SIDEBOARD_SERIAL_USART2_ENABLED || FEEDBACK_SERIAL_USART2_ENABLED || DEBUG_SERIAL_USART2_ENABLED)) {
        //#error CONTROL_PWM_LEFT_ENABLED and SERIAL_USART2 not allowed. It is on the same cable.
        while(1) { }
    }

    if (SUPPORT_BUTTONS_LEFT && (CONTROL_SERIAL_USART2_ENABLED || SIDEBOARD_SERIAL_USART2_ENABLED || FEEDBACK_SERIAL_USART2_ENABLED || DEBUG_SERIAL_USART2_ENABLED)) {
        //#error SUPPORT_BUTTONS_LEFT and SERIAL_USART2 not allowed. It is on the same cable.
        while(1) { }
    }

    if (SUPPORT_BUTTONS_LEFT && (CONTROL_ADC_ENABLED || CONTROL_PPM_LEFT_ENABLED || CONTROL_PWM_LEFT_ENABLED)) {
        //#error SUPPORT_BUTTONS_LEFT and (CONTROL_ADC_ENABLED or CONTROL_PPM_LEFT_ENABLED or CONTROL_PWM_LEFT_ENABLED) not allowed. It is on the same cable.
        while(1) { }
    }

    if (CONTROL_ADC_ENABLED && (CONTROL_PPM_LEFT_ENABLED || CONTROL_PWM_LEFT_ENABLED)) {
        //#error CONTROL_ADC_ENABLED and (CONTROL_PPM_LEFT_ENABLED or CONTROL_PWM_LEFT_ENABLED) not allowed. It is on the same cable.
        while(1) { }
    }

    if (CONTROL_PPM_LEFT_ENABLED && CONTROL_PWM_LEFT_ENABLED) {
        //#error CONTROL_PPM_LEFT_ENABLED and CONTROL_PWM_LEFT_ENABLED not allowed. It is on the same cable.
        while(1) { }
    }


    // RIGHT cable checks
    if (CONTROL_NUNCHUK_ENABLED && (CONTROL_SERIAL_USART3_ENABLED || SIDEBOARD_SERIAL_USART3_ENABLED || FEEDBACK_SERIAL_USART3_ENABLED || DEBUG_SERIAL_USART3_ENABLED)) {
        //#error CONTROL_NUNCHUK_ENABLED and SERIAL_USART3 not allowed. It is on the same cable.
        while(1) { }
    }

    if (CONTROL_PPM_RIGHT_ENABLED && (CONTROL_SERIAL_USART3_ENABLED || SIDEBOARD_SERIAL_USART3_ENABLED || FEEDBACK_SERIAL_USART3_ENABLED || DEBUG_SERIAL_USART3_ENABLED)) {
        //#error CONTROL_PPM_RIGHT_ENABLED and SERIAL_USART3 not allowed. It is on the same cable.
        while(1) { }
    }

    if (CONTROL_PWM_RIGHT_ENABLED && (CONTROL_SERIAL_USART3_ENABLED || SIDEBOARD_SERIAL_USART3_ENABLED || FEEDBACK_SERIAL_USART3_ENABLED || DEBUG_SERIAL_USART3_ENABLED)) {
        //#error CONTROL_PWM_RIGHT_ENABLED and SERIAL_USART3 not allowed. It is on the same cable.
        while(1) { }
    }

    if (DEBUG_I2C_LCD && (CONTROL_SERIAL_USART3_ENABLED || SIDEBOARD_SERIAL_USART3_ENABLED || FEEDBACK_SERIAL_USART3_ENABLED || DEBUG_SERIAL_USART3_ENABLED)) {
        //#error DEBUG_I2C_LCD and SERIAL_USART3 not allowed. It is on the same cable.
        while(1) { }
    }

    if (SUPPORT_BUTTONS_RIGHT && (CONTROL_SERIAL_USART3_ENABLED || SIDEBOARD_SERIAL_USART3_ENABLED || FEEDBACK_SERIAL_USART3_ENABLED || DEBUG_SERIAL_USART3_ENABLED)) {
        //#error SUPPORT_BUTTONS_RIGHT and SERIAL_USART3 not allowed. It is on the same cable.
        while(1) { }
    }

    if (SUPPORT_BUTTONS_RIGHT && (CONTROL_NUNCHUK_ENABLED || CONTROL_PPM_RIGHT_ENABLED || CONTROL_PWM_RIGHT_ENABLED || DEBUG_I2C_LCD)) {
        //#error SUPPORT_BUTTONS_RIGHT and (CONTROL_NUNCHUK_ENABLED or CONTROL_PPM_RIGHT_ENABLED or CONTROL_PWM_RIGHT_ENABLED or DEBUG_I2C_LCD) not allowed. It is on the same cable.
        while(1) { }
    }

    if (CONTROL_NUNCHUK_ENABLED && (CONTROL_PPM_RIGHT_ENABLED || CONTROL_PWM_RIGHT_ENABLED || DEBUG_I2C_LCD)) {
        //#error CONTROL_NUNCHUK_ENABLED and (CONTROL_PPM_RIGHT_ENABLED or CONTROL_PWM_RIGHT_ENABLED or DEBUG_I2C_LCD) not allowed. It is on the same cable.
        while(1) { }
    }

    if (DEBUG_I2C_LCD && (CONTROL_PPM_RIGHT_ENABLED || CONTROL_PWM_RIGHT_ENABLED)) {
        //#error DEBUG_I2C_LCD and (CONTROL_PPM_RIGHT_ENABLED or CONTROL_PWM_RIGHT_ENABLED) not allowed. It is on the same cable.
        while(1) { }
    }

    if (CONTROL_PPM_RIGHT_ENABLED && CONTROL_PWM_RIGHT_ENABLED) {
        //#error CONTROL_PPM_RIGHT_ENABLED and CONTROL_PWM_RIGHT_ENABLED not allowed. It is on the same cable.
        while(1) { }
    }


    // Functional checks
    if ((CONTROL_PPM_LEFT_ENABLED || CONTROL_PPM_RIGHT_ENABLED) && PPM_NUM_CHANNELS == 0) {
        //#error Total number of PPM channels needs to be set
        while(1) { }
    }
// ############################# END OF VALIDATE SETTINGS ############################
}